/**
 * Primary Mitoversity article for each catalog activity (1:1).
 * Stored on protocol meta as `articleId`; used for "Learn more" links.
 */
export const PROTOCOL_ARTICLE_IDS: Record<string, string> = {
  "sunrise-horizon": "sunrise-why",
  "sunrise-open-sky": "sunrise-why",
  "sunrise-outside": "sunrise-why",
  "sun-exposure": "solar-noon-vitamin-d",
  "sunset-viewing": "sunset-viewing-why",
  "red-nir-light": "red-nir-light",
  "barefoot-earth": "barefoot-earth",
  "nature-contact": "nature-contact",
  "low-d-hydration": "high-latitude-low-deuterium-water",
  "mineralized-water": "mineralized-water",
  "carbonated-water": "carbonated-water-co2",
  "baking-soda-water": "baking-soda-water",
  "hydration-timing": "hydration-timing",
  "castor-oil-navel": "castor-oil-navel",
  "deuterium-aware-meal": "deuterium-atp-synthase",
  "seafood-meal": "seafood-meal",
  "early-dinner": "early-dinner",
  "cold-face-plunge": "cold-face-plunge",
  "cold-thermogenesis": "cold-thermogenesis-skin-50",
  "reduce-nnemf-block": "reduce-nnemf-block",
  "magnetic-awareness": "earth-field-vs-geology",
  "phone-away-sleep": "phone-away-sleep",
  "air-tube-headphones": "air-tube-headphones",
  "magnetico-sleep-pad": "magnetico-sleep-pad",
  "breaker-off-bedroom": "breaker-off-bedroom",
  "breaker-off-office": "breaker-off-office",
  "morning-movement": "morning-movement",
  rebounding: "rebounding-lymphatic",
  "mastic-gum": "mastic-gum-chewing",
  "tuning-forks": "tuning-forks",
  "blue-light-hygiene": "blue-light-hygiene",
  "screen-light-hygiene": "screen-light-hygiene",
  "dark-bedroom": "true-dark-bedroom",
  "cool-bedroom-sleep": "cool-sleep-65",
  "consistent-sleep-window": "consistent-sleep-window",
};
